In [80]:
import numpy as np
import random
N=int(input('Enter number of lines '))
A=np.zeros((N,N),float)
rp=np.zeros((N),float)

for i in range(N):
    rp[i]=float(random.randint(1,4)) #filling the right part
                
for i in range(N): 
    if i==0:
        A[i,i], A[i,i+1] = float(random.randint(1,4)), float(random.randint(1,4))
    elif i==N-1:
        A[i,i-1], A[i,i] = float(random.randint(1,4)), float(random.randint(1,4))
    else:    
        A[i,i-1], A[i,i], A[i,i+1] = float(random.randint(1,4)), float(random.randint(1,4)), float(random.randint(1,4)) 

print(A)
print(rp)

for i in range (1,N):
    rp[i]*=-( A[i-1, i-1] / A[i, i-1] )
    A[i]*= -( A[i-1, i-1] / A[i, i-1] )
    A[i]+=A[i-1]
    rp[i]+=rp[i-1]
    
print(A) 

for i in range (N-2, -1, -1):
    
    rp[i]*=-( A[i+1, i+1] / A[i, i+1] )
    A[i]*= -( A[i+1, i+1] / A[i, i+1] )
    A[i]+=A[i+1]
    rp[i]+=rp[i+1]
    
print(A)  

for i in range (N):
    rp[i]/=A[i,i]
    print('x_', i+1, ' = ', round(rp[i],2), sep='')



Enter number of lines 4
[[2. 3. 0. 0.]
 [4. 1. 3. 0.]
 [0. 3. 1. 2.]
 [0. 0. 2. 1.]]
[1. 2. 3. 1.]
[[ 2.          3.          0.          0.        ]
 [ 0.          2.5        -1.5         0.        ]
 [ 0.          0.         -2.33333333 -1.66666667]
 [ 0.          0.          0.         -0.5       ]]
[[-0.77777778  0.          0.          0.        ]
 [ 0.          1.16666667  0.          0.        ]
 [ 0.          0.          0.7         0.        ]
 [ 0.          0.          0.         -0.5       ]]
x_1 = 1.25
x_2 = -0.5
x_3 = -0.83
x_4 = 2.67
