In [5]:
import numpy as np
import random

In [6]:
N=int(input())
x=[0]*N

for i in range(N):
    x[i]=None
values=np.zeros(N)
for i in range(N):
    values[i]=float(random.randint(1,7))
matrix=np.zeros((N,N))
for i in range(N):
    matrix[i,i]=float(random.randint(1,7))
    if i!=0:
        matrix[i,i-1]=float(random.randint(1,7))
    if i!=N-1:
        matrix[i,i+1]=float(random.randint(1,7))
print(matrix)
print(values)

for i in range(1,N):
    if matrix[i-1,i-1]!=0:
        k=matrix[i,i-1]/matrix[i-1,i-1]
        matrix[i]-=(matrix[i-1]*k)
        values[i]=values[i]-values[i-1]*k
    else:
        matrix[i],matrix[i-1]=matrix[i-1],matrix[i].copy()
        values[i],values[i-1]=values[i-1],values[i].copy()

for i in range(N):
    for j in range(N):
        matrix[i,j]=round(matrix[i,j],5)
flag=False

for i in range(N-1,-1,-1):
    for j in range(N-1,-1,-1):
        if matrix[i,j]!=0.:
            if x[j]==None:
                x[j]=values[i]/matrix[i,j]
            else:
                values[i]-=matrix[i,j]*x[j]
    if all(a==0 for a in matrix[i]) and values(i)!=0:
        flag=True
if flag==True:
    print('no solution')
else:
    for i in range(N):
        print('x_', i+1,' = ', round(float(x[i]),2), sep='')

33
[[4. 4. 0. ... 0. 0. 0.]
 [5. 6. 4. ... 0. 0. 0.]
 [0. 6. 7. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 5. 4. 0.]
 [0. 0. 0. ... 6. 4. 2.]
 [0. 0. 0. ... 0. 4. 7.]]
[5. 2. 3. 1. 6. 2. 7. 5. 3. 4. 6. 5. 7. 3. 7. 5. 2. 5. 2. 6. 2. 4. 4. 1.
 3. 3. 6. 4. 4. 5. 1. 4. 2.]
x_1 = 3.11
x_2 = -1.86
x_3 = -0.6
x_4 = 3.67
x_5 = -6.44
x_6 = 4.07
x_7 = 0.84
x_8 = -2.11
x_9 = 1.81
x_10 = 0.5
x_11 = -0.75
x_12 = 7.0
x_13 = -6.92
x_14 = 6.45
x_15 = -4.0
x_16 = 0.92
x_17 = 3.88
x_18 = -1.42
x_19 = -0.34
x_20 = 0.89
x_21 = 0.92
x_22 = -4.26
x_23 = 3.68
x_24 = -2.19
x_25 = -5.73
x_26 = 6.02
x_27 = -10.46
x_28 = 4.44
x_29 = 0.23
x_30 = -0.15
x_31 = 1.07
x_32 = -1.05
x_33 = 0.89
